services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=healthcare'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_USER=${DB_USER}'
    ports:
      - '3306'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}'
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}'
    ports:
      - '5672'
