spring.application.name=HealthCare-Platform
spring.docker.compose.enabled=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

prescription.storage-root=${user.home}/Desktop/HealthCare/healthcare-uploads/prescriptions
prescription.max-file-size=10485760

logging.level.com.yourpackage=DEBUG
logging.level.com.yourpackage.UserController=TRACE

logging.level.org.springframework=INFO

logging.level.org.hibernate=DEBUG

logging.file.name=application.log
logging.file.path=${user.home}/Desktop/HealthCare/logs/

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n