spring.application.name=HealthCare-Platform
spring.docker.compose.enabled=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

prescription.storage-root=${user.home}/healthcare-uploads/prescriptions
prescription.max-file-size=10485760